# Staging Deployment
name: Deploy to Staging
on:
  push:
    branches:
      - develop
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to Staging
      run: echo "Deploy commands here"
